### ISSUE TITLE
没有贴图的问题

### ISSUE THREAD

**Issue by Miaowu-Mecci** [MoYan1082/PMX_Model_Viewer_with_PhongLight#2]
在我尝试运行您的项目时，发现生成的模型上没有贴图，目前还未发现导致这个问题的原因。
![image](https://github.com/user-attachments/assets/cb81b92e-3235-4ce9-980d-ffea20b32ce4)

**Comment by MoYan1082** [comment]
修复了

**Comment by Miaowu-Mecci** [comment]
Thanks for your reply.
